language: ruby
rvm:
  - 2.2.2

before_install:
  # get rid of the installing activesupport (5.0.0)
  - gem install activesupport -v 4.2.6
  - gem install cocoapods

install:
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec jekyll build
  # the internally link won't check, if neccessay, just do
  - bundle exec htmlproofer ./_site --external_only --only-4xx
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer