language: ruby

sudo: required

before_install:
- sudo apt-add-repository ppa:brightbox/ruby-ng`
- sudo apt-get update`
- sudo apt-get install ruby2.3 ruby2.3-dev

install:
- bundle install --jobs=3 --retry=3

script: bundle exec jekyll server --quiet