language: python
python:
- '2.7'
install: pip install -r requirements/requirements.txt
script:
- cd sfm
- ./manage.py test --settings=sfm.settings.test_settings
notifications:
  email:
  - justinlittman@gmail.com