version: "2"
services:
    db:
        image: gwul/sfm-ui-db:master
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - TZ=${TZ}
        volumes_from:
            - data
    mq:
        image: rabbitmq@sha256:a5180a37b0baebb938ee9d12dd11eed64a909288d7f344e24771278f8a122367
        #RabbitMQ 3-management
        ports:
            - "15672:15672"
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
            - TZ=${TZ}
    data:
        image: ubuntu:14.04
        command: /bin/true
        volumes:
           - /sfm-data
        environment:
            - TZ=${TZ}
    ui:
        image: gwul/sfm-ui:${UI_TAG}
        ports:
            - "8080:80"
        links:
            - db:db
            - mq:mq
        environment:
            - SFM_DEBUG=${DEBUG}
            - SFM_APSCHEDULER_LOG=DEBUG
            - SFM_UI_LOG=DEBUG
            # This adds a 5 minute schedule option to speed testing.
            - SFM_FIVE_MINUTE_SCHEDULE=True
            - TZ=${TZ}
            - SFM_EMAIL_USER
            - SFM_EMAIL_PASSWORD
            - SFM_SMTP_HOST
            - SFM_HOST=localhost:8080
            - TWITTER_CONSUMER_KEY
            - TWITTER_CONSUMER_SECRET
            - WEIBO_API_KEY
            - WEIBO_API_SECRET
            - TUMBLR_CONSUMER_KEY
            - TUMBLR_CONSUMER_SECRET
            - RABBITMQ_USER
            - RABBITMQ_PASSWORD
            - POSTGRES_PASSWORD
            - LOAD_FIXTURES
            - SFM_REQS
        #volumes:
            # This links in your local code.
            #- "..:/opt/sfm-ui"
            # To also link in a local sfm-utils, uncomment this and set SFM_REQS to "dev" in .env
            #- "../../sfm-utils:/opt/sfm-utils"
        volumes_from:
            - data:ro
